project:
  type: website

website:
  title: "My Quarto Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "README"
        href: README.qmd

format:
  html:
    theme: cosmo
    toc: true

publish:
  gh-pages:
    branch: gh-pages
